### ISSUE TITLE
Reverse DDV/masher format video streams

### ISSUE THREAD

**Issue by paulsapps** [paulsapps/alive#1]
It is said that these are something like MPEG1 or the PSX STR/MDEC format. 

See this thread for a standalone EXE that plays and creates DDV files (useful for hacking the format no?).

http://www.oddworldforums.net/showthread.php?t=16421

The Masher/DDV video format is also used in the PC version of Metal Gear Solid.

Tiny bit of info here too:

http://mgsforums.com/topic/7180404/1/

**Comment by paulsapps** [comment]
This is happening here: https://github.com/paulsapps/MasherReversing

**Comment by MrSapps** [comment]
All DDV's now working, needs a huge tidy up though

**Comment by MrSapps** [comment]
Closing - the refactoring can be done as separate step - and the audio issue in VS2015 release build is covered by #24
