### ISSUE TITLE
Add PSX STR FMV support

### ISSUE THREAD

**Issue by paulsapps** [paulsapps/alive#5]
The PC version of AO's DDV's are actually just tweaked STR's.

**Comment by MrSapps** [comment]
Seems the PSX versions put many videos in one MOV file. Not sure how to know where to break them apart yet. JPSXDEC seems to be able to do it for the most part but it gets the AO demo splitting incorrect, not checked the AE demo yet.

**Comment by MrSapps** [comment]
Implemented in dev branch, but needs a clean up.
