### ISSUE TITLE
Support for Myst IV: Revelation?

### ISSUE THREAD

**Issue by annunaki2k2** [paulsapps/alive#62]
Is this open source "ALIVE" engine, based of the same "ALIVE" engine that powered Myst IV: Revelation? Or is that one totally different?

If it's the same, would it be possible to make your open source engine support playing Myst IV? If it's not, then please just reject this issue.

**Comment by MrSapps** [comment]
Unfortunately its not the same, this project is a re-implementation of ALIVE that powers Oddworld Abes Oddysee and Exoddus.
