### ISSUE TITLE
Some SEQ's have popping and crackling or sounds cut off early

### ISSUE THREAD

**Issue by MrSapps** [paulsapps/alive#8]
C1.LVL!OPTSNDFX.BSQ!7 pops and cracks like a mad man.
C1.LVL!OPTSNDFX.BSQ!1 plays the intro bird sound but the "chirp" sound cuts off about 30% of the way through playing the sample.

**Comment by MrSapps** [comment]
@mlgthatsme dunno if you have any ideas?

**Comment by mlgthatsme** [comment]
Ill have to look into it. I know there was crackling in some samples.

**Comment by MrSapps** [comment]
Btw I'm changing the sample format from float to u16 - don't know if there is any reason to keep float format?

**Comment by MrSapps** [comment]
I think I've broken everything by trying to change the audio format. helllp :(

**Comment by MrSapps** [comment]
Closing as most of these are fixed, will add remaining work into #24
